name: gnw
description: "A new Flutter project."
publish_to: 'none'


version: 1.1.4+8

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.3

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  flutter_riverpod: ^2.6.1
  image_picker: ^1.0.7
  http: ^1.2.1
  shared_preferences: ^2.3.2
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  in_app_update: ^4.2.5
  firebase_core: ^4.12.1
  firebase_crashlytics: ^5.2.6
  fluttertoast: ^9.1.0
  firebase_messaging: ^16.4.3
  firebase_in_app_messaging: ^0.9.2+6
  path_provider: ^2.1.1
  flutter_cache_manager: ^3.4.2
  syncfusion_flutter_pdfviewer: ^33.2.13
  open_filex: ^4.7.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/LOGO.png"
#  adaptive_icon_foreground: "lib/images/GNW_RED_LOGO.png"


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/adi-registration.properties
    - assets/security_certificate.crt
    - lib/images/
    - lib/icons/
    - lib/icons/user.svg
    - lib/PDF/Doctors.pdf
