// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqSgGZjdeuRFGj8UefWhLTHHf2wjlM08g',
    appId: '1:438834589175:web:fba2224b78fd27c94b12f2',
    messagingSenderId: '438834589175',
    projectId: 'gnwbazaar-24520',
    authDomain: 'gnwbazaar-24520.firebaseapp.com',
    storageBucket: 'gnwbazaar-24520.firebasestorage.app',
    measurementId: 'G-54SBLHNKB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJl_1HTkkMvjEZNsr3qW8Ltg-J4XdMIHs',
    appId: '1:438834589175:android:c6d12eb64f39ea664b12f2',
    messagingSenderId: '438834589175',
    projectId: 'gnwbazaar-24520',
    storageBucket: 'gnwbazaar-24520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4WD0kY8VbY02B_xGwMxo-3d0SGe34oc',
    appId: '1:438834589175:ios:896a8e85135182204b12f2',
    messagingSenderId: '438834589175',
    projectId: 'gnwbazaar-24520',
    storageBucket: 'gnwbazaar-24520.firebasestorage.app',
    iosBundleId: 'com.example.gnw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH4WD0kY8VbY02B_xGwMxo-3d0SGe34oc',
    appId: '1:438834589175:ios:896a8e85135182204b12f2',
    messagingSenderId: '438834589175',
    projectId: 'gnwbazaar-24520',
    storageBucket: 'gnwbazaar-24520.firebasestorage.app',
    iosBundleId: 'com.example.gnw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqSgGZjdeuRFGj8UefWhLTHHf2wjlM08g',
    appId: '1:438834589175:web:768af6dbd4d631cf4b12f2',
    messagingSenderId: '438834589175',
    projectId: 'gnwbazaar-24520',
    authDomain: 'gnwbazaar-24520.firebaseapp.com',
    storageBucket: 'gnwbazaar-24520.firebasestorage.app',
    measurementId: 'G-6D87FJWPZD',
  );
}
